{
 "title": "Speedcast Fleet Edge Devices",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "SimpleJsonVariable" }
  ]
 },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "target": "select metric", "type": "timeserie" }
   ]
  },
  {
   "title": "Position",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 11, "w": 10, "x": 6, "y": 0 },
   "valueName": "current",
   "targets": [
    { "target": "FBBTerminal_Latitude", "type": "table" },
    { "target": "FBBTerminal_Longitude", "type": "table" }
   ]
  },
  {
   "title": "SVN Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "target": "Cisco5921_svn:svn_status", "type": "timeserie" },
    { "target": "Cisco5921_svn:svn_status_code", "type": "timeserie" }
   ]
  },
  {
   "title": "SVN Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "Cisco5921_svn:svn_status", "type": "timeserie" }
   ]
  },
  {
   "title": "BUC Fan Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "IDirectCoreModule_BUCFanStatus", "type": "timeserie" }
   ]
  },
  {
   "title": "BUC Temperature ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "target": "IDirectCoreModule_BUCTemp", "type": "timeserie" }
   ]
  },
  {
   "title": "Global Beam Name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "IDirectCoreModule_GlobalBeamName",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Current Beam Number",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "IDirectCoreModule_CurrentBeamNumber",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "SVN Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "target": "Cisco5921_svn:svn_status", "type": "timeserie" }
   ]
  },
  {
   "title": "TX Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "IDirectCoreModule_TXPower", "type": "timeserie" }
   ]
  },
  {
   "title": "RX SNR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "IDirectCoreModule_RXSNR", "type": "timeserie" }
   ]
  }
 ]
}